services:
  - type: web
    name: tienda-backend-api
    runtime: python3
    buildCommand: "./build.sh"
    startCommand: "gunicorn Backend.wsgi:application"
    plan: free
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: tienda-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: Backend.render_settings
      - key: WEB_CONCURRENCY
        value: 4
      - key: CLOUDINARY_CLOUD_NAME
        value: do1ntnlop
      - key: CLOUDINARY_API_KEY
        value: 117225377115856
      - key: CLOUDINARY_API_SECRET
        value: e0YSrk3sT_70-ijM6mwdFBIWP9w
      - key: DJANGO_CLOUDINARY_STORAGE
        value: true

databases:
  - name: tienda-db
    databaseName: tienda_production
    user: tienda_user
    plan: free

buildCommand: |
  pip install --upgrade pip
  pip install -r requirements.txt
  python fix_db_migrations.py 