# Generated by Django 5.2.4 on 2025-08-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categoriaproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Categoría de producto', 'verbose_name_plural': 'Categorías de productos'},
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='categoriaproducto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='activa',
            field=models.BooleanField(default=True, help_text='Indica si la categoría está disponible', verbose_name='Categoría activa'),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='descripcion',
            field=models.TextField(blank=True, default=1, help_text='Descripción detallada de la categoría', verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa de la categoría', null=True, upload_to='categorias/', verbose_name='Imagen de la categoría'),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo de la categoría', max_length=100, unique=True, verbose_name='Nombre de la categoría'),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='slug',
            field=models.SlugField(help_text='Identificador único para URLs', max_length=120, unique=True, verbose_name='Slug para URL'),
        ),
        migrations.AddIndex(
            model_name='categoriaproducto',
            index=models.Index(fields=['nombre'], name='categorias__nombre_cbe9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriaproducto',
            index=models.Index(fields=['slug'], name='categorias__slug_aa9e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriaproducto',
            index=models.Index(fields=['activa'], name='categorias__activa_354dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='categoriaproducto',
            index=models.Index(fields=['orden'], name='categorias__orden_a60610_idx'),
        ),
    ]
