# Generated by Django 5.2.4 on 2025-08-03 19:22

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_alter_categoriaproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='categorias/', verbose_name='Imagen representativa'),
        ),
    ]
