# Generated by Django 5.2.4 on 2025-08-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0010_fix_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproducto',
            name='slug',
            field=models.SlugField(
                blank=True,
                help_text='Identificador único para URLs',
                max_length=120,
                null=True,
                unique=True,
                verbose_name='Slug para URL'
            ),
        ),
    ]
