# Generated by Django 5.2.4 on 2025-08-04 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0010_fix_slug_field'),
    ]

    operations = [
    ]
