# Generated by Django 5.2.4 on 2025-08-03 19:22

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_remove_producto_categorias_secundarias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='imagen',
            field=models.ImageField(help_text='Imagen del producto en este color', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='productos/colores/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_principal',
            field=models.ImageField(blank=True, help_text='Imagen destacada del producto', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='productos/', verbose_name='Imagen principal'),
        ),
    ]
