# Generated by Django 5.2.4 on 2025-08-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_fix_datetime_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador único para URLs', max_length=220, null=True, unique=True, verbose_name='Slug para URL'),
        ),
    ]
